// <auto-generated />
using System;
using Aggregator.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aggregator.DataAccess.Migrations
{
    [DbContext(typeof(AggregatorDbContext))]
    [Migration("20250512063605_NotificationDetailsRelations")]
    partial class NotificationDetailsRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("nepc")
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Aggregator.DataAccess.Entities.ABSEntities.Account", b =>
                {
                    b.Property<string>("AccountNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CurrencyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(417);

                    b.Property<string>("AccountGroup")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte>("AccountTypeID")
                        .HasColumnType("tinyint");

                    b.Property<string>("BalanceGroup")
                        .IsRequired()
                        .HasColumnType("char(5)");

                    b.Property<DateTime?>("CloseDate")
                        .HasColumnType("date");

                    b.Property<string>("Codename")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("CtSumN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(15,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("CtSumV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(15,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("CurrentBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(15,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("CurrentNationalBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(15,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<decimal>("DtSumN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(15,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("DtSumV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(15,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("OfficeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OpenDate")
                        .HasColumnType("date");

                    b.HasKey("AccountNo", "CurrencyID")
                        .HasName("PK_Accounts");

                    b.ToTable("Accounts", "dbo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.ABSEntities.Office", b =>
                {
                    b.Property<string>("DeviceCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AccountNoIncome")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AccountNoTransit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("AdditionalDeviceType")
                        .HasColumnType("int");

                    b.Property<string>("Adress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("CashBack")
                        .HasColumnType("numeric(15,2)");

                    b.Property<int>("CityID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CloseDate")
                        .HasColumnType("date");

                    b.Property<byte>("ComisionType")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("Comission")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(15,2)")
                        .HasDefaultValue(0m);

                    b.Property<int?>("CustomProcess")
                        .HasColumnType("int");

                    b.Property<int?>("DataProcessingMethodID")
                        .HasColumnType("int");

                    b.Property<int?>("DeviceAffiliationTypeID")
                        .HasColumnType("int");

                    b.Property<int?>("DeviceAudioOutputTypeID")
                        .HasColumnType("int");

                    b.Property<int?>("DeviceInstallationTypeID")
                        .HasColumnType("int");

                    b.Property<int?>("DeviceLocationTypeID")
                        .HasColumnType("int");

                    b.Property<int?>("DeviceModelID")
                        .HasColumnType("int");

                    b.Property<int?>("DeviceProducerID")
                        .HasColumnType("int");

                    b.Property<int?>("DeviceRampTypeID")
                        .HasColumnType("int");

                    b.Property<int?>("DeviceTouchTypingTypeID")
                        .HasColumnType("int");

                    b.Property<int>("DeviceTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("IDDevice");

                    b.Property<TimeSpan?>("FinishTime")
                        .HasColumnType("time");

                    b.Property<decimal>("FriendCommission")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(15,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime?>("InstallationDate")
                        .HasColumnType("date");

                    b.Property<int?>("InsuranceСoverageTypeID")
                        .HasColumnType("int");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("Location")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<int>("MainOfficeID")
                        .HasColumnType("int");

                    b.Property<string>("MccCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NameDevice")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("OfficeIDIn")
                        .HasColumnType("int");

                    b.Property<decimal>("OperationMonthPlan")
                        .HasColumnType("numeric(15,2)");

                    b.Property<int?>("OperationSystemID")
                        .HasColumnType("int");

                    b.Property<string>("Owner")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("RBODeviceTypeID")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("time");

                    b.Property<decimal>("TotalComission")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(15,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("DeviceCode")
                        .HasName("PK_Cards_Offices");

                    b.ToTable("Office", "Cards", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.ABSEntities.PushNotificationSettings", b =>
                {
                    b.Property<int>("LoginID")
                        .HasColumnType("int");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LanguageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("LastRequestDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("LoginName")
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("LoginID", "CustomerID")
                        .HasName("PK_Settings");

                    b.ToTable("Settings", "PushNotification", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.Abstract.Notification", b =>
                {
                    b.Property<long>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("NotificationId"));

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<int>("NotificationType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("NotificationId");

                    b.ToTable("Notifications", "nepc");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.AccountInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AccountsInfoId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<long?>("AcctBalChangeNotificationId")
                        .HasColumnType("bigint");

                    b.Property<long?>("IssFinAuthNotificationId")
                        .HasColumnType("bigint");

                    b.Property<long>("NotificationId")
                        .HasColumnType("bigint");

                    b.Property<int>("NotificationType")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AcctBalChangeNotificationId");

                    b.HasIndex("IssFinAuthNotificationId");

                    b.ToTable("AccountInfo", "nepc");
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.AccountsInfoLimitWrapper", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountsInfoId")
                        .HasColumnType("bigint");

                    b.Property<long>("CardInfoId")
                        .HasColumnType("bigint");

                    b.Property<long>("LimitId")
                        .HasColumnType("bigint");

                    b.Property<byte>("LimitType")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("AccountsInfoId");

                    b.HasIndex("LimitId");

                    b.ToTable("AccountsInfoLimitWrappers", "nepc");
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.AcctBalChange.AcctBalChangeDetails", b =>
                {
                    b.Property<long>("AcctBalChangeDetailsId")
                        .HasColumnType("bigint");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<long?>("FinTransId")
                        .HasColumnType("bigint");

                    b.Property<string>("IssInstId")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<long>("NotificationId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Reversal")
                        .HasColumnType("bit");

                    b.Property<int>("TransType")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TransactionTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("AcctBalChangeDetailsId");

                    b.HasIndex("FinTransId");

                    b.HasIndex("NotificationId")
                        .IsUnique();

                    b.ToTable("AcctBalChangeDetails", "nepc");
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.AcqFinAuth.AcqFinAuthDetails", b =>
                {
                    b.Property<long>("AcqFinAuthDetailsId")
                        .HasColumnType("bigint");

                    b.Property<string>("AccountId")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("AcqFeeDirection")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("ApprovalCode")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("AuthDirection")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("AuthorizationCondition")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("CorrespondingAccount")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("ExpDate")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateTimeOffset>("LocalTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("NotificationId")
                        .HasColumnType("bigint");

                    b.Property<bool>("PhysTerm")
                        .HasColumnType("bit");

                    b.Property<string>("PosEntryMode")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int>("ResponseCode")
                        .HasMaxLength(6)
                        .HasColumnType("int");

                    b.Property<bool>("Reversal")
                        .HasColumnType("bit");

                    b.Property<string>("Rrn")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("ServiceCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("ServiceId")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<int>("TransType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TransactionTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("AcqFinAuthDetailsId");

                    b.HasIndex("NotificationId")
                        .IsUnique();

                    b.ToTable("AcqFinAuthDetails", "nepc");
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.AcsOtp.AcsOtpDetails", b =>
                {
                    b.Property<long>("DetailsId")
                        .HasColumnType("bigint");

                    b.Property<long>("NotificationId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("TransactionTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("DetailsId");

                    b.HasIndex("NotificationId")
                        .IsUnique();

                    b.ToTable("AcsOtpDetails", "nepc");
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.CardInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ContractId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("ExpDate")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("MobilePhone")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("RefPan")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("CardInfos", "nepc");
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.CardInfoLimitWrapper", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CardInfoId")
                        .HasColumnType("bigint");

                    b.Property<long>("LimitId")
                        .HasColumnType("bigint");

                    b.Property<byte>("LimitType")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("CardInfoId");

                    b.HasIndex("LimitId");

                    b.ToTable("CardInfoLimitWrappers", "nepc");
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.CardStatusChange.CardStatusChangeDetails", b =>
                {
                    b.Property<long>("CardStatusChangeDetailsId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("ChangeDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ExpDate")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int>("NewStatus")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<long>("NotificationId")
                        .HasColumnType("bigint");

                    b.Property<int>("OldStatus")
                        .HasColumnType("int");

                    b.Property<string>("Service")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UserName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("CardStatusChangeDetailsId");

                    b.HasIndex("NotificationId")
                        .IsUnique();

                    b.ToTable("CardStatusChangeDetails", "nepc");
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.CheckedLimit", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<bool>("Exceeded")
                        .HasColumnType("bit");

                    b.Property<long>("IssFinAuthDetailsId")
                        .HasColumnType("bigint");

                    b.Property<byte>("ObjectType")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("IssFinAuthDetailsId");

                    b.ToTable("CheckedLimits", "nepc");
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.ExtensionParameter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long>("NotificationExtensionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NotificationExtensionId");

                    b.ToTable("ExtensionParameters", "nepc");
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.FinTransaction", b =>
                {
                    b.Property<long>("FinTransactionId")
                        .HasColumnType("bigint");

                    b.Property<string>("CorrespondingAccountType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direction")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("FeTrans")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<long?>("MerchantInfoId")
                        .HasColumnType("bigint");

                    b.HasKey("FinTransactionId");

                    b.HasIndex("MerchantInfoId")
                        .IsUnique()
                        .HasFilter("[MerchantInfoId] IS NOT NULL");

                    b.ToTable("FinTransactions", "nepc");
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.InboxArchiveMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("InboxArchiveMessages", "nepc");
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.IssFinAuth.IssFinAuthDetails", b =>
                {
                    b.Property<long>("IssFinAuthDetailsId")
                        .HasColumnType("bigint");

                    b.Property<string>("AccountId")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("AcqFeeDirection")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("ApprovalCode")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("AuthDirection")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("AuthorizationCondition")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("CorrespondingAccount")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Dpan")
                        .HasMaxLength(19)
                        .HasColumnType("nvarchar(19)");

                    b.Property<string>("IssFeeDirection")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("IssInstId")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateTimeOffset>("LocalTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("NotificationId")
                        .HasColumnType("bigint");

                    b.Property<int>("ResponseCode")
                        .HasMaxLength(6)
                        .HasColumnType("int");

                    b.Property<bool>("Reversal")
                        .HasColumnType("bit");

                    b.Property<string>("Rrn")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<long?>("SvTrace")
                        .HasColumnType("bigint");

                    b.Property<int>("TransType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TransactionTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("IssFinAuthDetailsId");

                    b.HasIndex("NotificationId")
                        .IsUnique();

                    b.ToTable("IssFinAuthDetails", "nepc");
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.Limit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int?>("CycleLength")
                        .HasColumnType("int");

                    b.Property<string>("CycleType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("LimitId")
                        .HasColumnType("bigint");

                    b.Property<byte>("LimitType")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("TrsValue")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal>("UsedValue")
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("Id");

                    b.ToTable("Limits", "nepc");
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.MerchantInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Aid")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("City")
                        .HasMaxLength(31)
                        .HasColumnType("nvarchar(31)");

                    b.Property<string>("Country")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Mcc")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("MerchantId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Street")
                        .HasMaxLength(31)
                        .HasColumnType("nvarchar(31)");

                    b.Property<string>("TerminalId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("MerchantInfos", "nepc");
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.NotificationExtension", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Critical")
                        .HasColumnType("bit");

                    b.Property<string>("ExtensionId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("NotificationId")
                        .HasColumnType("bigint");

                    b.Property<int>("NotificationType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId");

                    b.HasIndex("ExtensionId", "NotificationId")
                        .IsUnique();

                    b.ToTable("NotificationExtensions", "nepc");
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.NotificationMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NotificationMessages", "nepc");
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.OwiUserAction.OwiUserActionDetails", b =>
                {
                    b.Property<long>("OwiUserActionDetailsId")
                        .HasColumnType("bigint");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<long>("NotificationId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("TransactionTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("OwiUserActionDetailsId");

                    b.HasIndex("NotificationId")
                        .IsUnique();

                    b.ToTable("OwiUserActionDetails", "nepc");
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.PinChange.PinChangeDetails", b =>
                {
                    b.Property<long>("PinChangeDetailsId")
                        .HasColumnType("bigint");

                    b.Property<string>("ExpDate")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<long>("NotificationId")
                        .HasColumnType("bigint");

                    b.Property<int?>("ResponseCode")
                        .HasMaxLength(6)
                        .HasColumnType("int");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("TransactionTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("PinChangeDetailsId");

                    b.HasIndex("NotificationId")
                        .IsUnique();

                    b.ToTable("PinChangeDetails", "nepc");
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.TokenChangeStatus.TokenStatusChangeDetails", b =>
                {
                    b.Property<long>("TokenStatusChangeDetailsId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("ChangeDate")
                        .HasMaxLength(14)
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DeviceType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DpanExpDate")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("DpanRef")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)");

                    b.Property<string>("FpanRef")
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)");

                    b.Property<long>("NotificationId")
                        .HasColumnType("bigint");

                    b.Property<string>("PaymentSystem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("WalletProvider")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("TokenStatusChangeDetailsId");

                    b.HasIndex("NotificationId")
                        .IsUnique();

                    b.ToTable("TokenStatusChangeDetails", "nepc");
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.Unhold.UnholdDetails", b =>
                {
                    b.Property<long>("UnholdDetailsId")
                        .HasColumnType("bigint");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ApprovalCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("CorrespondingAccount")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Dpan")
                        .HasMaxLength(19)
                        .HasColumnType("nvarchar(19)");

                    b.Property<string>("IssFeeDirection")
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTimeOffset>("LocalTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("NotificationId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Reversal")
                        .HasColumnType("bit");

                    b.Property<string>("Rrn")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<long?>("SvTrace")
                        .HasColumnType("bigint");

                    b.Property<int>("TransType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TransactionTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UnholdDirection")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("UnholdDetailsId");

                    b.HasIndex("NotificationId")
                        .IsUnique();

                    b.ToTable("UnholdDetails", "nepc");
                });

            modelBuilder.Entity("DataIngrestorApi.DataAccess.Entities.InboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("InboxMessages", "nepc", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.AcctBalChange.AcctBalChange", b =>
                {
                    b.HasBaseType("Aggregator.DataAccess.Entities.Abstract.Notification");

                    b.Property<long>("CardInfoId")
                        .HasColumnType("bigint");

                    b.HasIndex("CardInfoId");

                    b.ToTable("AcctBalChanges", "nepc");
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.AcqFinAuth.AcqFinAuth", b =>
                {
                    b.HasBaseType("Aggregator.DataAccess.Entities.Abstract.Notification");

                    b.Property<long>("MerchantInfoId")
                        .HasColumnType("bigint");

                    b.HasIndex("MerchantInfoId");

                    b.ToTable("AcqFinAuths", "nepc");
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.AcsOtp.AcsOtp", b =>
                {
                    b.HasBaseType("Aggregator.DataAccess.Entities.Abstract.Notification");

                    b.Property<long>("CardInfoId")
                        .HasColumnType("bigint");

                    b.HasIndex("CardInfoId");

                    b.ToTable("AcsOtps", "nepc");
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.CardStatusChange.CardStatusChange", b =>
                {
                    b.HasBaseType("Aggregator.DataAccess.Entities.Abstract.Notification");

                    b.Property<long>("CardInfoId")
                        .HasColumnType("bigint");

                    b.HasIndex("CardInfoId");

                    b.ToTable("CardStatusChanges", "nepc");
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.IssFinAuth.IssFinAuth", b =>
                {
                    b.HasBaseType("Aggregator.DataAccess.Entities.Abstract.Notification");

                    b.Property<long?>("CardInfoId")
                        .HasColumnType("bigint");

                    b.Property<long>("MerchantInfoId")
                        .HasColumnType("bigint");

                    b.HasIndex("CardInfoId");

                    b.HasIndex("MerchantInfoId");

                    b.ToTable("IssFinAuths", "nepc");
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.OwiUserAction.OwiUserAction", b =>
                {
                    b.HasBaseType("Aggregator.DataAccess.Entities.Abstract.Notification");

                    b.Property<long?>("CardInfoId")
                        .HasColumnType("bigint");

                    b.HasIndex("CardInfoId");

                    b.ToTable("OwiUserActions", "nepc");
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.PinChange.PinChange", b =>
                {
                    b.HasBaseType("Aggregator.DataAccess.Entities.Abstract.Notification");

                    b.Property<long>("CardInfoId")
                        .HasColumnType("bigint");

                    b.HasIndex("CardInfoId");

                    b.ToTable("PinChanges", "nepc");
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.TokenChangeStatus.TokenStatusChange", b =>
                {
                    b.HasBaseType("Aggregator.DataAccess.Entities.Abstract.Notification");

                    b.Property<long>("CardInfoId")
                        .HasColumnType("bigint");

                    b.HasIndex("CardInfoId");

                    b.ToTable("TokenStatusChanges", "nepc");
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.Unhold.Unhold", b =>
                {
                    b.HasBaseType("Aggregator.DataAccess.Entities.Abstract.Notification");

                    b.Property<long>("CardInfoId")
                        .HasColumnType("bigint");

                    b.Property<long>("MerchantInfoId")
                        .HasColumnType("bigint");

                    b.HasIndex("CardInfoId");

                    b.HasIndex("MerchantInfoId");

                    b.ToTable("Unholds", "nepc");
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.AccountInfo", b =>
                {
                    b.HasOne("Aggregator.DataAccess.Entities.AcctBalChange.AcctBalChange", null)
                        .WithMany("AccountsInfo")
                        .HasForeignKey("AcctBalChangeNotificationId");

                    b.HasOne("Aggregator.DataAccess.Entities.IssFinAuth.IssFinAuth", null)
                        .WithMany("AccountsInfo")
                        .HasForeignKey("IssFinAuthNotificationId");

                    b.OwnsOne("Aggregator.DataAccess.Entities.OwnedEntities.ExceedLimitMoney", "ExceedLimit", b1 =>
                        {
                            b1.Property<long>("AccountInfoId")
                                .HasColumnType("bigint");

                            b1.Property<decimal?>("Amount")
                                .HasColumnType("decimal(15,2)");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)");

                            b1.HasKey("AccountInfoId");

                            b1.ToTable("AccountInfo", "nepc");

                            b1.WithOwner()
                                .HasForeignKey("AccountInfoId");
                        });

                    b.OwnsOne("Aggregator.DataAccess.Entities.OwnedEntities.AviableBalance", "AviableBalance", b1 =>
                        {
                            b1.Property<long>("AccountInfoId")
                                .HasColumnType("bigint");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(15,2)");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)");

                            b1.HasKey("AccountInfoId");

                            b1.ToTable("AccountInfo", "nepc");

                            b1.WithOwner()
                                .HasForeignKey("AccountInfoId");
                        });

                    b.Navigation("AviableBalance")
                        .IsRequired();

                    b.Navigation("ExceedLimit")
                        .IsRequired();
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.AccountsInfoLimitWrapper", b =>
                {
                    b.HasOne("Aggregator.DataAccess.Entities.AccountInfo", "AccountInfo")
                        .WithMany("Limits")
                        .HasForeignKey("AccountsInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aggregator.DataAccess.Entities.Limit", "Limit")
                        .WithMany()
                        .HasForeignKey("LimitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountInfo");

                    b.Navigation("Limit");
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.AcctBalChange.AcctBalChangeDetails", b =>
                {
                    b.HasOne("Aggregator.DataAccess.Entities.FinTransaction", "FinTrans")
                        .WithMany()
                        .HasForeignKey("FinTransId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Aggregator.DataAccess.Entities.AcctBalChange.AcctBalChange", null)
                        .WithOne("Details")
                        .HasForeignKey("Aggregator.DataAccess.Entities.AcctBalChange.AcctBalChangeDetails", "NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Aggregator.DataAccess.Entities.OwnedEntities.AccountBalance", "AccountBalance", b1 =>
                        {
                            b1.Property<long>("AcctBalChangeDetailsId")
                                .HasColumnType("bigint");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(15,2)");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)");

                            b1.HasKey("AcctBalChangeDetailsId");

                            b1.ToTable("AcctBalChangeDetails", "nepc");

                            b1.WithOwner()
                                .HasForeignKey("AcctBalChangeDetailsId");
                        });

                    b.OwnsOne("Aggregator.DataAccess.Entities.OwnedEntities.AccountAmount", "AccountAmount", b1 =>
                        {
                            b1.Property<long>("AcctBalChangeDetailsId")
                                .HasColumnType("bigint");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(15,2)");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)");

                            b1.HasKey("AcctBalChangeDetailsId");

                            b1.ToTable("AcctBalChangeDetails", "nepc");

                            b1.WithOwner()
                                .HasForeignKey("AcctBalChangeDetailsId");
                        });

                    b.OwnsOne("Aggregator.DataAccess.Entities.OwnedEntities.Authorization", "Auth", b1 =>
                        {
                            b1.Property<long>("AcctBalChangeDetailsId")
                                .HasColumnType("bigint");

                            b1.Property<long?>("Id")
                                .HasColumnType("bigint");

                            b1.Property<bool?>("Reversal")
                                .HasColumnType("bit");

                            b1.HasKey("AcctBalChangeDetailsId");

                            b1.ToTable("AcctBalChangeDetails", "nepc");

                            b1.WithOwner()
                                .HasForeignKey("AcctBalChangeDetailsId");
                        });

                    b.Navigation("AccountAmount")
                        .IsRequired();

                    b.Navigation("AccountBalance")
                        .IsRequired();

                    b.Navigation("Auth")
                        .IsRequired();

                    b.Navigation("FinTrans");
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.AcqFinAuth.AcqFinAuthDetails", b =>
                {
                    b.HasOne("Aggregator.DataAccess.Entities.AcqFinAuth.AcqFinAuth", null)
                        .WithOne("Details")
                        .HasForeignKey("Aggregator.DataAccess.Entities.AcqFinAuth.AcqFinAuthDetails", "NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Aggregator.DataAccess.Entities.OwnedEntities.AcqFee", "AcqFee", b1 =>
                        {
                            b1.Property<long>("AcqFinAuthDetailsId")
                                .HasColumnType("bigint");

                            b1.Property<decimal?>("Amount")
                                .HasColumnType("decimal(15,2)");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)");

                            b1.HasKey("AcqFinAuthDetailsId");

                            b1.ToTable("AcqFinAuthDetails", "nepc");

                            b1.WithOwner()
                                .HasForeignKey("AcqFinAuthDetailsId");
                        });

                    b.OwnsOne("Aggregator.DataAccess.Entities.OwnedEntities.AuthMoney", "AuthMoney", b1 =>
                        {
                            b1.Property<long>("AcqFinAuthDetailsId")
                                .HasColumnType("bigint");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(15,2)");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)");

                            b1.HasKey("AcqFinAuthDetailsId");

                            b1.ToTable("AcqFinAuthDetails", "nepc");

                            b1.WithOwner()
                                .HasForeignKey("AcqFinAuthDetailsId");
                        });

                    b.OwnsOne("Aggregator.DataAccess.Entities.OwnedEntities.CardIdentifier", "CardIdentifier", b1 =>
                        {
                            b1.Property<long>("AcqFinAuthDetailsId")
                                .HasColumnType("bigint");

                            b1.Property<int?>("CardIdentifierType")
                                .HasColumnType("int");

                            b1.Property<string>("CardIdentifierValue")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("AcqFinAuthDetailsId");

                            b1.ToTable("AcqFinAuthDetails", "nepc");

                            b1.WithOwner()
                                .HasForeignKey("AcqFinAuthDetailsId");
                        });

                    b.OwnsOne("Aggregator.DataAccess.Entities.OwnedEntities.ConvMoney", "ConvMoney", b1 =>
                        {
                            b1.Property<long>("AcqFinAuthDetailsId")
                                .HasColumnType("bigint");

                            b1.Property<decimal?>("Amount")
                                .HasColumnType("decimal(15,2)");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)");

                            b1.HasKey("AcqFinAuthDetailsId");

                            b1.ToTable("AcqFinAuthDetails", "nepc");

                            b1.WithOwner()
                                .HasForeignKey("AcqFinAuthDetailsId");
                        });

                    b.Navigation("AcqFee")
                        .IsRequired();

                    b.Navigation("AuthMoney")
                        .IsRequired();

                    b.Navigation("CardIdentifier")
                        .IsRequired();

                    b.Navigation("ConvMoney")
                        .IsRequired();
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.AcsOtp.AcsOtpDetails", b =>
                {
                    b.HasOne("Aggregator.DataAccess.Entities.AcsOtp.AcsOtp", null)
                        .WithOne("Details")
                        .HasForeignKey("Aggregator.DataAccess.Entities.AcsOtp.AcsOtpDetails", "NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Aggregator.DataAccess.Entities.OwnedEntities.AuthMoney", "AuthMoney", b1 =>
                        {
                            b1.Property<long>("AcsOtpDetailsDetailsId")
                                .HasColumnType("bigint");

                            b1.Property<decimal?>("Amount")
                                .HasColumnType("decimal(15,2)");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)");

                            b1.HasKey("AcsOtpDetailsDetailsId");

                            b1.ToTable("AcsOtpDetails", "nepc");

                            b1.WithOwner()
                                .HasForeignKey("AcsOtpDetailsDetailsId");
                        });

                    b.OwnsOne("Aggregator.DataAccess.Entities.OwnedEntities.OtpInfo", "OtpInfo", b1 =>
                        {
                            b1.Property<long>("AcsOtpDetailsDetailsId")
                                .HasColumnType("bigint");

                            b1.Property<DateTimeOffset>("ExpirationTime")
                                .HasColumnType("datetimeoffset");

                            b1.Property<string>("Otp")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("AcsOtpDetailsDetailsId");

                            b1.ToTable("AcsOtpDetails", "nepc");

                            b1.WithOwner()
                                .HasForeignKey("AcsOtpDetailsDetailsId");
                        });

                    b.Navigation("AuthMoney");

                    b.Navigation("OtpInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.CardInfo", b =>
                {
                    b.OwnsOne("Aggregator.DataAccess.Entities.OwnedEntities.CardIdentifier", "CardIdentifier", b1 =>
                        {
                            b1.Property<long>("CardInfoId")
                                .HasColumnType("bigint");

                            b1.Property<int?>("CardIdentifierType")
                                .HasColumnType("int");

                            b1.Property<string>("CardIdentifierValue")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("CardInfoId");

                            b1.ToTable("CardInfos", "nepc");

                            b1.WithOwner()
                                .HasForeignKey("CardInfoId");
                        });

                    b.Navigation("CardIdentifier")
                        .IsRequired();
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.CardInfoLimitWrapper", b =>
                {
                    b.HasOne("Aggregator.DataAccess.Entities.CardInfo", "CardInfo")
                        .WithMany("Limits")
                        .HasForeignKey("CardInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aggregator.DataAccess.Entities.Limit", "Limit")
                        .WithMany()
                        .HasForeignKey("LimitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardInfo");

                    b.Navigation("Limit");
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.CardStatusChange.CardStatusChangeDetails", b =>
                {
                    b.HasOne("Aggregator.DataAccess.Entities.CardStatusChange.CardStatusChange", null)
                        .WithOne("Details")
                        .HasForeignKey("Aggregator.DataAccess.Entities.CardStatusChange.CardStatusChangeDetails", "NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Aggregator.DataAccess.Entities.OwnedEntities.CardIdentifier", "CardIdentifier", b1 =>
                        {
                            b1.Property<long>("CardStatusChangeDetailsId")
                                .HasColumnType("bigint");

                            b1.Property<int?>("CardIdentifierType")
                                .HasColumnType("int");

                            b1.Property<string>("CardIdentifierValue")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("CardStatusChangeDetailsId");

                            b1.ToTable("CardStatusChangeDetails", "nepc");

                            b1.WithOwner()
                                .HasForeignKey("CardStatusChangeDetailsId");
                        });

                    b.Navigation("CardIdentifier")
                        .IsRequired();
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.CheckedLimit", b =>
                {
                    b.HasOne("Aggregator.DataAccess.Entities.IssFinAuth.IssFinAuthDetails", null)
                        .WithMany("CheckedLimits")
                        .HasForeignKey("IssFinAuthDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.ExtensionParameter", b =>
                {
                    b.HasOne("Aggregator.DataAccess.Entities.NotificationExtension", "Extension")
                        .WithMany("ExtensionParameters")
                        .HasForeignKey("NotificationExtensionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Extension");
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.FinTransaction", b =>
                {
                    b.HasOne("Aggregator.DataAccess.Entities.MerchantInfo", "MerchantInfo")
                        .WithOne()
                        .HasForeignKey("Aggregator.DataAccess.Entities.FinTransaction", "MerchantInfoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Aggregator.DataAccess.Entities.OwnedEntities.TranMoney", "TranMoney", b1 =>
                        {
                            b1.Property<long>("FinTransactionId")
                                .HasColumnType("bigint");

                            b1.Property<decimal?>("Amount")
                                .HasColumnType("decimal(15,2)");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)");

                            b1.HasKey("FinTransactionId");

                            b1.ToTable("FinTransactions", "nepc");

                            b1.WithOwner()
                                .HasForeignKey("FinTransactionId");
                        });

                    b.Navigation("MerchantInfo");

                    b.Navigation("TranMoney")
                        .IsRequired();
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.IssFinAuth.IssFinAuthDetails", b =>
                {
                    b.HasOne("Aggregator.DataAccess.Entities.IssFinAuth.IssFinAuth", null)
                        .WithOne("Details")
                        .HasForeignKey("Aggregator.DataAccess.Entities.IssFinAuth.IssFinAuthDetails", "NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Aggregator.DataAccess.Entities.OwnedEntities.AccountBalance", "AccountBalance", b1 =>
                        {
                            b1.Property<long>("IssFinAuthDetailsId")
                                .HasColumnType("bigint");

                            b1.Property<decimal?>("Amount")
                                .HasColumnType("decimal(15,2)");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)");

                            b1.HasKey("IssFinAuthDetailsId");

                            b1.ToTable("IssFinAuthDetails", "nepc");

                            b1.WithOwner()
                                .HasForeignKey("IssFinAuthDetailsId");
                        });

                    b.OwnsOne("Aggregator.DataAccess.Entities.OwnedEntities.AcqFee", "AcqFee", b1 =>
                        {
                            b1.Property<long>("IssFinAuthDetailsId")
                                .HasColumnType("bigint");

                            b1.Property<decimal?>("Amount")
                                .HasColumnType("decimal(15,2)");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)");

                            b1.HasKey("IssFinAuthDetailsId");

                            b1.ToTable("IssFinAuthDetails", "nepc");

                            b1.WithOwner()
                                .HasForeignKey("IssFinAuthDetailsId");
                        });

                    b.OwnsOne("Aggregator.DataAccess.Entities.OwnedEntities.AuthMoney", "AuthMoney", b1 =>
                        {
                            b1.Property<long>("IssFinAuthDetailsId")
                                .HasColumnType("bigint");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(15,2)");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)");

                            b1.HasKey("IssFinAuthDetailsId");

                            b1.ToTable("IssFinAuthDetails", "nepc");

                            b1.WithOwner()
                                .HasForeignKey("IssFinAuthDetailsId");
                        });

                    b.OwnsOne("Aggregator.DataAccess.Entities.OwnedEntities.CardIdentifier", "CardIdentifier", b1 =>
                        {
                            b1.Property<long>("IssFinAuthDetailsId")
                                .HasColumnType("bigint");

                            b1.Property<int?>("CardIdentifierType")
                                .HasColumnType("int");

                            b1.Property<string>("CardIdentifierValue")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("IssFinAuthDetailsId");

                            b1.ToTable("IssFinAuthDetails", "nepc");

                            b1.WithOwner()
                                .HasForeignKey("IssFinAuthDetailsId");
                        });

                    b.OwnsOne("Aggregator.DataAccess.Entities.OwnedEntities.ConvMoney", "ConvMoney", b1 =>
                        {
                            b1.Property<long>("IssFinAuthDetailsId")
                                .HasColumnType("bigint");

                            b1.Property<decimal?>("Amount")
                                .HasColumnType("decimal(15,2)");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)");

                            b1.HasKey("IssFinAuthDetailsId");

                            b1.ToTable("IssFinAuthDetails", "nepc");

                            b1.WithOwner()
                                .HasForeignKey("IssFinAuthDetailsId");
                        });

                    b.OwnsOne("Aggregator.DataAccess.Entities.OwnedEntities.IssFee", "IssFee", b1 =>
                        {
                            b1.Property<long>("IssFinAuthDetailsId")
                                .HasColumnType("bigint");

                            b1.Property<decimal?>("Amount")
                                .HasColumnType("decimal(15,2)");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)");

                            b1.HasKey("IssFinAuthDetailsId");

                            b1.ToTable("IssFinAuthDetails", "nepc");

                            b1.WithOwner()
                                .HasForeignKey("IssFinAuthDetailsId");
                        });

                    b.OwnsOne("Aggregator.DataAccess.Entities.OwnedEntities.WalletProvider", "WalletProvider", b1 =>
                        {
                            b1.Property<long>("IssFinAuthDetailsId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Id")
                                .HasMaxLength(11)
                                .HasColumnType("nvarchar(11)");

                            b1.Property<string>("PaymentSystem")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("IssFinAuthDetailsId");

                            b1.ToTable("IssFinAuthDetails", "nepc");

                            b1.WithOwner()
                                .HasForeignKey("IssFinAuthDetailsId");
                        });

                    b.OwnsOne("Aggregator.DataAccess.Entities.OwnedEntities.AuthMoneyDetails", "AuthMoneyDetails", b1 =>
                        {
                            b1.Property<long>("IssFinAuthDetailsId")
                                .HasColumnType("bigint");

                            b1.HasKey("IssFinAuthDetailsId");

                            b1.ToTable("IssFinAuthDetails", "nepc");

                            b1.WithOwner()
                                .HasForeignKey("IssFinAuthDetailsId");

                            b1.OwnsOne("Aggregator.DataAccess.Entities.OwnedEntities.ExceedLimitMoney", "ExceedLimitMoney", b2 =>
                                {
                                    b2.Property<long>("AuthMoneyDetailsIssFinAuthDetailsId")
                                        .HasColumnType("bigint");

                                    b2.Property<decimal?>("Amount")
                                        .HasColumnType("decimal(15,2)");

                                    b2.Property<string>("Currency")
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("AuthMoneyDetailsIssFinAuthDetailsId");

                                    b2.ToTable("IssFinAuthDetails", "nepc");

                                    b2.WithOwner()
                                        .HasForeignKey("AuthMoneyDetailsIssFinAuthDetailsId");
                                });

                            b1.OwnsOne("Aggregator.DataAccess.Entities.OwnedEntities.OwnFundsMoney", "OwnFundsMoney", b2 =>
                                {
                                    b2.Property<long>("AuthMoneyDetailsIssFinAuthDetailsId")
                                        .HasColumnType("bigint");

                                    b2.Property<decimal?>("Amount")
                                        .HasColumnType("decimal(15,2)");

                                    b2.Property<string>("Currency")
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("AuthMoneyDetailsIssFinAuthDetailsId");

                                    b2.ToTable("IssFinAuthDetails", "nepc");

                                    b2.WithOwner()
                                        .HasForeignKey("AuthMoneyDetailsIssFinAuthDetailsId");
                                });

                            b1.Navigation("ExceedLimitMoney")
                                .IsRequired();

                            b1.Navigation("OwnFundsMoney")
                                .IsRequired();
                        });

                    b.OwnsOne("Aggregator.DataAccess.Entities.OwnedEntities.BillingMoney", "BillingMoney", b1 =>
                        {
                            b1.Property<long>("IssFinAuthDetailsId")
                                .HasColumnType("bigint");

                            b1.Property<decimal?>("Amount")
                                .HasColumnType("decimal(15,2)");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)");

                            b1.HasKey("IssFinAuthDetailsId");

                            b1.ToTable("IssFinAuthDetails", "nepc");

                            b1.WithOwner()
                                .HasForeignKey("IssFinAuthDetailsId");
                        });

                    b.Navigation("AccountBalance")
                        .IsRequired();

                    b.Navigation("AcqFee")
                        .IsRequired();

                    b.Navigation("AuthMoney")
                        .IsRequired();

                    b.Navigation("AuthMoneyDetails")
                        .IsRequired();

                    b.Navigation("BillingMoney")
                        .IsRequired();

                    b.Navigation("CardIdentifier")
                        .IsRequired();

                    b.Navigation("ConvMoney")
                        .IsRequired();

                    b.Navigation("IssFee")
                        .IsRequired();

                    b.Navigation("WalletProvider")
                        .IsRequired();
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.NotificationExtension", b =>
                {
                    b.HasOne("Aggregator.DataAccess.Entities.Abstract.Notification", "Notification")
                        .WithMany("Extensions")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.OwiUserAction.OwiUserActionDetails", b =>
                {
                    b.HasOne("Aggregator.DataAccess.Entities.OwiUserAction.OwiUserAction", null)
                        .WithOne("Details")
                        .HasForeignKey("Aggregator.DataAccess.Entities.OwiUserAction.OwiUserActionDetails", "NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.PinChange.PinChangeDetails", b =>
                {
                    b.HasOne("Aggregator.DataAccess.Entities.PinChange.PinChange", null)
                        .WithOne("Details")
                        .HasForeignKey("Aggregator.DataAccess.Entities.PinChange.PinChangeDetails", "NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Aggregator.DataAccess.Entities.OwnedEntities.CardIdentifier", "CardIdentifier", b1 =>
                        {
                            b1.Property<long>("PinChangeDetailsId")
                                .HasColumnType("bigint");

                            b1.Property<int?>("CardIdentifierType")
                                .HasColumnType("int");

                            b1.Property<string>("CardIdentifierValue")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PinChangeDetailsId");

                            b1.ToTable("PinChangeDetails", "nepc");

                            b1.WithOwner()
                                .HasForeignKey("PinChangeDetailsId");
                        });

                    b.Navigation("CardIdentifier")
                        .IsRequired();
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.TokenChangeStatus.TokenStatusChangeDetails", b =>
                {
                    b.HasOne("Aggregator.DataAccess.Entities.TokenChangeStatus.TokenStatusChange", null)
                        .WithOne("Details")
                        .HasForeignKey("Aggregator.DataAccess.Entities.TokenChangeStatus.TokenStatusChangeDetails", "NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Aggregator.DataAccess.Entities.OwnedEntities.CardIdentifier", "CardIdentifier", b1 =>
                        {
                            b1.Property<long>("TokenStatusChangeDetailsId")
                                .HasColumnType("bigint");

                            b1.Property<int?>("CardIdentifierType")
                                .HasColumnType("int");

                            b1.Property<string>("CardIdentifierValue")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TokenStatusChangeDetailsId");

                            b1.ToTable("TokenStatusChangeDetails", "nepc");

                            b1.WithOwner()
                                .HasForeignKey("TokenStatusChangeDetailsId");
                        });

                    b.Navigation("CardIdentifier")
                        .IsRequired();
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.Unhold.UnholdDetails", b =>
                {
                    b.HasOne("Aggregator.DataAccess.Entities.Unhold.Unhold", null)
                        .WithOne("Details")
                        .HasForeignKey("Aggregator.DataAccess.Entities.Unhold.UnholdDetails", "NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Aggregator.DataAccess.Entities.OwnedEntities.UnholdMoney", "UnholdMoney", b1 =>
                        {
                            b1.Property<long>("UnholdDetailsId")
                                .HasColumnType("bigint");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(15,2)");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)");

                            b1.HasKey("UnholdDetailsId");

                            b1.ToTable("UnholdDetails", "nepc");

                            b1.WithOwner()
                                .HasForeignKey("UnholdDetailsId");
                        });

                    b.OwnsOne("Aggregator.DataAccess.Entities.OwnedEntities.AuthMoney", "AuthMoney", b1 =>
                        {
                            b1.Property<long>("UnholdDetailsId")
                                .HasColumnType("bigint");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(15,2)");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)");

                            b1.HasKey("UnholdDetailsId");

                            b1.ToTable("UnholdDetails", "nepc");

                            b1.WithOwner()
                                .HasForeignKey("UnholdDetailsId");
                        });

                    b.OwnsOne("Aggregator.DataAccess.Entities.OwnedEntities.CardIdentifier", "CardIdentifier", b1 =>
                        {
                            b1.Property<long>("UnholdDetailsId")
                                .HasColumnType("bigint");

                            b1.Property<int?>("CardIdentifierType")
                                .HasColumnType("int");

                            b1.Property<string>("CardIdentifierValue")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UnholdDetailsId");

                            b1.ToTable("UnholdDetails", "nepc");

                            b1.WithOwner()
                                .HasForeignKey("UnholdDetailsId");
                        });

                    b.OwnsOne("Aggregator.DataAccess.Entities.OwnedEntities.IssFee", "IssFee", b1 =>
                        {
                            b1.Property<long>("UnholdDetailsId")
                                .HasColumnType("bigint");

                            b1.Property<decimal?>("Amount")
                                .HasColumnType("decimal(15,2)");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)");

                            b1.HasKey("UnholdDetailsId");

                            b1.ToTable("UnholdDetails", "nepc");

                            b1.WithOwner()
                                .HasForeignKey("UnholdDetailsId");
                        });

                    b.OwnsOne("Aggregator.DataAccess.Entities.OwnedEntities.WalletProvider", "WalletProvider", b1 =>
                        {
                            b1.Property<long>("UnholdDetailsId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Id")
                                .HasMaxLength(11)
                                .HasColumnType("nvarchar(11)");

                            b1.Property<string>("PaymentSystem")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UnholdDetailsId");

                            b1.ToTable("UnholdDetails", "nepc");

                            b1.WithOwner()
                                .HasForeignKey("UnholdDetailsId");
                        });

                    b.Navigation("AuthMoney")
                        .IsRequired();

                    b.Navigation("CardIdentifier")
                        .IsRequired();

                    b.Navigation("IssFee")
                        .IsRequired();

                    b.Navigation("UnholdMoney")
                        .IsRequired();

                    b.Navigation("WalletProvider")
                        .IsRequired();
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.AcctBalChange.AcctBalChange", b =>
                {
                    b.HasOne("Aggregator.DataAccess.Entities.CardInfo", "CardInfo")
                        .WithMany()
                        .HasForeignKey("CardInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aggregator.DataAccess.Entities.Abstract.Notification", null)
                        .WithOne()
                        .HasForeignKey("Aggregator.DataAccess.Entities.AcctBalChange.AcctBalChange", "NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardInfo");
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.AcqFinAuth.AcqFinAuth", b =>
                {
                    b.HasOne("Aggregator.DataAccess.Entities.MerchantInfo", "MerchantInfo")
                        .WithMany()
                        .HasForeignKey("MerchantInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aggregator.DataAccess.Entities.Abstract.Notification", null)
                        .WithOne()
                        .HasForeignKey("Aggregator.DataAccess.Entities.AcqFinAuth.AcqFinAuth", "NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MerchantInfo");
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.AcsOtp.AcsOtp", b =>
                {
                    b.HasOne("Aggregator.DataAccess.Entities.CardInfo", "CardInfo")
                        .WithMany()
                        .HasForeignKey("CardInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aggregator.DataAccess.Entities.Abstract.Notification", null)
                        .WithOne()
                        .HasForeignKey("Aggregator.DataAccess.Entities.AcsOtp.AcsOtp", "NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Aggregator.DataAccess.Entities.OwnedEntities.AcsOtpMerchantInfo", "MerchantInfo", b1 =>
                        {
                            b1.Property<long>("AcsOtpNotificationId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)");

                            b1.Property<string>("MerchantId")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("nvarchar(15)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(25)
                                .HasColumnType("nvarchar(25)");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)");

                            b1.HasKey("AcsOtpNotificationId");

                            b1.ToTable("AcsOtps", "nepc");

                            b1.WithOwner()
                                .HasForeignKey("AcsOtpNotificationId");
                        });

                    b.Navigation("CardInfo");

                    b.Navigation("MerchantInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.CardStatusChange.CardStatusChange", b =>
                {
                    b.HasOne("Aggregator.DataAccess.Entities.CardInfo", "CardInfo")
                        .WithMany()
                        .HasForeignKey("CardInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aggregator.DataAccess.Entities.Abstract.Notification", null)
                        .WithOne()
                        .HasForeignKey("Aggregator.DataAccess.Entities.CardStatusChange.CardStatusChange", "NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardInfo");
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.IssFinAuth.IssFinAuth", b =>
                {
                    b.HasOne("Aggregator.DataAccess.Entities.CardInfo", "CardInfo")
                        .WithMany()
                        .HasForeignKey("CardInfoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Aggregator.DataAccess.Entities.MerchantInfo", "MerchantInfo")
                        .WithMany()
                        .HasForeignKey("MerchantInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aggregator.DataAccess.Entities.Abstract.Notification", null)
                        .WithOne()
                        .HasForeignKey("Aggregator.DataAccess.Entities.IssFinAuth.IssFinAuth", "NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardInfo");

                    b.Navigation("MerchantInfo");
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.OwiUserAction.OwiUserAction", b =>
                {
                    b.HasOne("Aggregator.DataAccess.Entities.CardInfo", "CardInfo")
                        .WithMany()
                        .HasForeignKey("CardInfoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Aggregator.DataAccess.Entities.Abstract.Notification", null)
                        .WithOne()
                        .HasForeignKey("Aggregator.DataAccess.Entities.OwiUserAction.OwiUserAction", "NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardInfo");
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.PinChange.PinChange", b =>
                {
                    b.HasOne("Aggregator.DataAccess.Entities.CardInfo", "CardInfo")
                        .WithMany()
                        .HasForeignKey("CardInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aggregator.DataAccess.Entities.Abstract.Notification", null)
                        .WithOne()
                        .HasForeignKey("Aggregator.DataAccess.Entities.PinChange.PinChange", "NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardInfo");
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.TokenChangeStatus.TokenStatusChange", b =>
                {
                    b.HasOne("Aggregator.DataAccess.Entities.CardInfo", "CardInfo")
                        .WithMany()
                        .HasForeignKey("CardInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aggregator.DataAccess.Entities.Abstract.Notification", null)
                        .WithOne()
                        .HasForeignKey("Aggregator.DataAccess.Entities.TokenChangeStatus.TokenStatusChange", "NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardInfo");
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.Unhold.Unhold", b =>
                {
                    b.HasOne("Aggregator.DataAccess.Entities.CardInfo", "CardInfo")
                        .WithMany()
                        .HasForeignKey("CardInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aggregator.DataAccess.Entities.MerchantInfo", "MerchantInfo")
                        .WithMany()
                        .HasForeignKey("MerchantInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aggregator.DataAccess.Entities.Abstract.Notification", null)
                        .WithOne()
                        .HasForeignKey("Aggregator.DataAccess.Entities.Unhold.Unhold", "NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardInfo");

                    b.Navigation("MerchantInfo");
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.Abstract.Notification", b =>
                {
                    b.Navigation("Extensions");
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.AccountInfo", b =>
                {
                    b.Navigation("Limits");
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.CardInfo", b =>
                {
                    b.Navigation("Limits");
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.IssFinAuth.IssFinAuthDetails", b =>
                {
                    b.Navigation("CheckedLimits");
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.NotificationExtension", b =>
                {
                    b.Navigation("ExtensionParameters");
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.AcctBalChange.AcctBalChange", b =>
                {
                    b.Navigation("AccountsInfo");

                    b.Navigation("Details")
                        .IsRequired();
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.AcqFinAuth.AcqFinAuth", b =>
                {
                    b.Navigation("Details")
                        .IsRequired();
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.AcsOtp.AcsOtp", b =>
                {
                    b.Navigation("Details")
                        .IsRequired();
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.CardStatusChange.CardStatusChange", b =>
                {
                    b.Navigation("Details")
                        .IsRequired();
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.IssFinAuth.IssFinAuth", b =>
                {
                    b.Navigation("AccountsInfo");

                    b.Navigation("Details")
                        .IsRequired();
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.OwiUserAction.OwiUserAction", b =>
                {
                    b.Navigation("Details")
                        .IsRequired();
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.PinChange.PinChange", b =>
                {
                    b.Navigation("Details")
                        .IsRequired();
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.TokenChangeStatus.TokenStatusChange", b =>
                {
                    b.Navigation("Details")
                        .IsRequired();
                });

            modelBuilder.Entity("Aggregator.DataAccess.Entities.Unhold.Unhold", b =>
                {
                    b.Navigation("Details")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
